name: Link Check

on:
  pull_request:
  push:
    branches:
      - master
      - main

permissions:
  contents: read

jobs:
  linkcheck:
    name: Link check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Link check
        uses: lycheeverse/lychee-action@v2
        with:
          args: --config lychee.toml "README.md" "website/**/*.html" "docs/**/*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
