name: Spell Check

on:
  pull_request:
  push:
    branches:
      - master
      - main

permissions:
  contents: read

jobs:
  spellcheck:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Spell check
        uses: streetsidesoftware/cspell-action@v6
        with:
          config: cspell.json
